name: Sebastien Phaneuf
markdown: kramdown
theme: jekyll-theme-slate
title: Tech, Games and Whisky
description: The Sebr's Blog

markdown: kramdown

baseurl: ""
url: https://codinfox.github.io
# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: '' # leave blank if you don't want disqus
