name: Sebastien Phaneuf
markdown: kramdown
theme: jekyll-theme-slate
title: Techs, Games and Whisky
description: Sebastien's Phaneuf Blog

markdown: kramdown

baseurl: ""
url: https://codinfox.github.io

google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
